"""JSON output for the dashboard export.

The committed data/*.json files are 2-space indented with a trailing
newline, unescaped UTF-8, and a forward slash escaped wherever it follows
`<`. That formatting is a contract: deviating turns the first
regeneration into an unreviewable whole-file diff.
"""

import json
import re
from pathlib import Path
from typing import Any

_NON_ALNUM = re.compile(r"[^A-Za-z0-9]+")
_INDENT = "  "
_MAX_INLINE_WIDTH = 80

# write_rows renders a scalar-only array inline -- "[a, b, c]" on the same
# line as its key -- as long as that line stays under _MAX_INLINE_WIDTH
# columns; wider than that, or any array holding a dict or a nested list,
# expands one element per line instead. json.dumps's `indent` option makes
# no such distinction -- it expands every array regardless of width -- so
# write_rows walks the structure itself instead of delegating straight to
# json.dumps.
#
# This is an EMPIRICAL fit against the committed artifact, not a verified
# transcription of jsonlite's algorithm. The threshold and the "measure
# without a trailing comma" rule were reverse-engineered by measuring every
# array in the committed data/table1.json: the widest line an inline array
# actually produced was 79 columns, the narrowest an expanded one produced
# was 80, with zero exceptions across 252 array instances -- 63 rows times
# the 4 list columns, 243 inline and 9 expanded (element count alone does
# not predict it -- both 1-element and 5-element arrays appear
# inline elsewhere in the file). But the jsonlite version installed in this
# repo (2.0.0) does NOT reproduce the rule: its scalar-vector collapse path
# (collapse.R / collapse_pretty.c) has no width branch at all, and
# toJSON(letters[1:20], pretty = TRUE) inlines a 20-element vector
# unconditionally on this machine. The committed file was almost certainly
# generated by a different jsonlite version than the one now installed. If
# this threshold ever needs revisiting, re-derive it from the committed
# data, not from reading jsonlite's current source.
#
# write_value does not need any of this: its one caller with array content
# (geocoded_trials.json) already expands arrays one element per line, which
# is what indent=2 produces unmodified.
_SCALAR_TYPES = (str, int, float, bool, type(None))


def to_camel(name: str) -> str:
    """Convert a display column name to its camelCase JSON key.

    The remainder is lower-cased before capitalising so mid-name acronyms
    normalise too: "Registry ID" -> "registryId", never "registryID".
    Note this is not idempotent on already-camelCase input -- it splits
    only on non-alphanumeric runs, so to_camel("chromosomalLocation")
    returns "chromosomallocation". That is correct for its real input
    (display names) and is not a bug.
    """
    parts = _NON_ALNUM.sub(" ", name).strip().split()
    if not parts:
        return ""
    head, *tail = parts
    return head.lower() + "".join(word.capitalize() for word in tail)


def _escape_slashes(text: str) -> str:
    """Apply jsonlite's forward-slash escaping to already-encoded JSON.

    jsonlite escapes `/` when, and only when, it immediately follows `<`
    -- the XSS-safety rule for JSON embedded in a <script> block -- so
    `</b>` is written `<\\/b>` while `http://a/b` and `1/2` are left
    alone. Verified against jsonlite 2.0.0 and against the committed
    data/refs.json, whose 22 rows carry 44 escaped slashes after `<` and
    29 unescaped ones elsewhere. Python's json.dumps never escapes `/`,
    so without this every one of those rows rewrites on the first
    regeneration -- exactly the whole-file diff the module docstring's
    contract exists to prevent.

    Rewriting the encoded text rather than the source string is safe:
    neither `<` nor `/` is JSON syntax, and json.dumps emits neither from
    an escape sequence, so every `<` and `/` in the output is a literal
    character out of a string or a key.
    """
    return text.replace("</", "<\\/")


def _encode_scalar(value: Any) -> str:
    return _escape_slashes(json.dumps(value, ensure_ascii=False))


def _encode_array(items: list[Any], level: int, prefix: str = "") -> str:
    """Encode one JSON array, matching the committed file's layout (see the
    module comment above for where the threshold comes from).

    A list of scalars is a candidate for inlining as "[" + ", ".join(...) +
    "]", but only actually inlines if the whole line it would occupy --
    `prefix` plus the array text itself, trailing comma excluded -- stays
    under _MAX_INLINE_WIDTH columns. `prefix` must be the exact text that
    will precede this array on its rendered line: indent plus the quoted
    key and ": " when it is an object value, or just the indent when it is
    itself an element of another array. A caller that omits it for a
    nested array undercounts the true width and can wrongly inline
    something that should expand -- see _encode_array's own call below,
    which passes `inner` for exactly this reason. An empty list vacuously
    qualifies as scalar-only and, being 2 columns wide, always inlines as
    "[]". Anything wider, or any array holding a dict or a nested list,
    expands one element per line instead.
    """
    if all(isinstance(item, _SCALAR_TYPES) for item in items):
        inline = "[" + ", ".join(_encode_scalar(item) for item in items) + "]"
        if len(prefix) + len(inline) < _MAX_INLINE_WIDTH:
            return inline
    inner = _INDENT * (level + 1)
    outer = _INDENT * level
    lines = [inner + _encode_value(item, level + 1, inner) for item in items]
    return "[\n" + ",\n".join(lines) + "\n" + outer + "]"


def _encode_object(obj: dict[str, Any], level: int) -> str:
    if not obj:
        return "{}"
    inner = _INDENT * (level + 1)
    outer = _INDENT * level
    lines = []
    for key, value in obj.items():
        prefix = f"{inner}{_encode_scalar(key)}: "
        lines.append(f"{prefix}{_encode_value(value, level + 1, prefix)}")
    return "{\n" + ",\n".join(lines) + "\n" + outer + "}"


def _encode_value(value: Any, level: int, prefix: str = "") -> str:
    if isinstance(value, dict):
        return _encode_object(value, level)
    if isinstance(value, list):
        return _encode_array(value, level, prefix)
    return _encode_scalar(value)


def write_rows(rows: list[dict[str, Any]], path: Path) -> None:
    """Write rows as a JSON array of objects, keys camelCased.

    Python lists serialise as JSON arrays unconditionally, so the four
    Gene list-columns need no equivalent of R's I() wrapping. The layout of
    those arrays still has to match the committed file -- inlined under
    _MAX_INLINE_WIDTH columns, expanded past it -- so this goes through
    _encode_value rather than plain json.dumps. See _encode_array.
    """
    camel_rows = [{to_camel(k): v for k, v in row.items()} for row in rows]
    text = _encode_value(camel_rows, 0)
    path.write_text(text + "\n", encoding="utf-8")


def write_value(value: Any, path: Path) -> None:
    """Write a single JSON value — an object, or a bare null."""
    text = _escape_slashes(json.dumps(value, indent=2, ensure_ascii=False))
    path.write_text(text + "\n", encoding="utf-8")
