import type { Answers } from "./answers.ts";
import { clean, wrap80 } from "./generate/json.ts";
import { KEY } from "./validate.ts";

/** The archive's file name; the checklist unpacks the newest one saved. */
export const BUNDLE_NAME = "disease-adaptation.zip";

/**
 * The remaining steps of docs/adapting-to-your-disease.md with the disease
 * key written into every command. Steps 2 and 3 of the guide (the
 * interview and the disease/ files) are what the wizard did.
 */
export function renderChecklist(answers: Answers): string {
  const { disease } = answers.identity;
  // The Review step shows this for an unfinished draft as well, and a
  // command built from a blank key runs as written, creating a role called
  // `_user`. An answer that is missing, or a key validate() refuses, reads
  // as the guide's placeholder instead; the archive is only built from a
  // draft that passes, so its copy is whole.
  const key = KEY.test(clean(disease.key)) ? clean(disease.key) : "<key>";
  const name = clean(disease.name) || "<disease name>";
  const abbreviation = clean(disease.abbreviation) || "<abbreviation>";
  // The repository and the Deploy project are named with a hyphen where
  // the key has an underscore: the project's name becomes a host name, and
  // a host name holds no underscore. The database names keep the key.
  const project = `${key.replaceAll("_", "-")}-dashboard`;
  const stem = BUNDLE_NAME.replace(/\.zip$/, "");
  const lines = [
    `# Adapting the dashboard to ${name} (${abbreviation})`,
    "",
    "The files in this archive were generated by the dashboard's adapt wizard. This checklist is the rest of the work, in order; the full guide is docs/adapting-to-your-disease.md in the repository and explains every step.",
    "",
    "## 1. Fork and clone",
    "",
    `Fork the repository on GitHub as \`${project}\`, then:`,
    "",
    `    git clone https://github.com/<your-account>/${project}.git`,
    `    cd ${project}`,
    "    git remote add upstream https://github.com/mathieubpoiriericm/csvd-dashboard.git",
    "    deno install",
    "    uv sync --group dev --group figure",
    "    deno task e2e:install",
    "",
    "The last line installs the browser tests and downloads the Chromium build they drive. On Linux, add the system libraries Chromium needs as well:",
    "",
    "    npx --prefix e2e playwright install --with-deps chromium",
    "",
    "## 2. Unpack this archive into the clone",
    "",
    `From the clone's root: remove the upstream institute's logos, unpack \`disease/\` and \`static/\` from the archive over the clone's, delete the upstream recall baseline, then format the prose and the uploaded logo. A browser saves a later download as \`${stem} (1).zip\` beside the first, so the second line unpacks whichever archive is newest; delete the older ones.`,
    "",
    "    git rm -q static/institute/logo-light.svg static/institute/logo-dark.svg",
    `    unzip -o "$(ls -t <path-to>/${stem}*.zip | head -1)" 'disease/*' 'static/*'`,
    "    rm disease/recall_baseline.json",
    "    deno fmt disease/ static/institute/",
    "",
    "## 3. Start from empty data",
    "",
    "The upstream disease's recall cassettes go with its test trees: step 6 records this disease's own, and a cassette left in place would be replayed instead.",
    "",
    "    deno task data:empty",
    "    git rm -r tests/csvd e2e/tests/csvd tests/pipeline/csvd tests/scripts/csvd",
    "    git rm -r tests/pipeline/cassettes/test_query_recall_gold",
    "",
    "## 4. The edits outside disease/",
    "",
    "- In `tests/pipeline/test_prompt_vocabulary.py`, set `_ADMITTED_UNASKED = {}`.",
    "- In `e2e/package.json`, rename `name` and `description` for your dashboard.",
    "- If a check below reports a hit in `tests/no_disease_literals_test.ts` or `tests/pipeline/test_no_disease_literals.py`: a hit is a line holding one of your terms as a whole word. Reword it when it is about your disease; when it is a unit, an identifier or an unrelated code, add an entry with the reason to the test's allow-list (`ALLOWED` or `_ALLOWED`), as its message says.",
    "",
    "## 5. Run the checks",
    "",
    "    deno task check",
    "    deno task test:coverage",
    "    uv run ruff check .",
    "    uv run ty check",
    "    uv run pytest --cov=pipeline --cov=pipeline/alembic --cov-branch --cov-report=term-missing:skip-covered",
    "    uv run pytest tests/scripts",
    "    npx --prefix e2e playwright test -c e2e/playwright.config.ts",
    "",
    "A failure names the file and the key. Fix it in `disease/` and run the command again.",
    "",
    "## 6. Measure cost and recall",
    "",
    "    uv run python -m pipeline.main --test-mode --days-back 365",
    "",
    "Multiply the papers-per-year figure by 0.09 USD. Above about 2,000 papers a year, remove the broadest marker terms in `disease/pipeline.json` (each one adds papers) or make them more specific; a shorter phrase matches more. If a MeSH heading there is a broad parent, replace it with a narrower one.",
    "",
    "    uv run python -m scripts.measure_recall",
    "    uv run python -m scripts.measure_recall --write-baseline",
    "    uv run pytest tests/pipeline/test_query_recall_gold.py --record-mode=once",
    "",
    "## 7. Secrets, database and first commit",
    "",
    "    cp .env.example .env",
    "    openssl rand -base64 32",
    "",
    "Fill `.env`:",
    "",
    "- `DASHBOARD_PASSPHRASE`: a sentence; it is the shared login. Wrap it in single quotes, as `DASHBOARD_PASSPHRASE='…'`, and keep apostrophes out of it: unquoted, Deno reads a `#` as the start of a comment and a `$` as a variable.",
    "- `DASHBOARD_SESSION_SECRET`: the random value above.",
    `- \`DB_NAME=${key}_dashboard\`, \`DB_USER=${key}_user\` and a \`DB_PASSWORD\`; the pipeline refuses to start without all three.`,
    "- `ANTHROPIC_API_KEY`, `ENTREZ_EMAIL` and `UNPAYWALL_EMAIL`.",
    "- `NCBI_API_KEY` is optional, and `.env.example` leaves it commented out. Uncomment it only to set a real key: NCBI answers any other value, an empty one included, with HTTP 400 on every call.",
    "",
    "Then create the database. `createuser -P` asks for the role's password twice: type the `DB_PASSWORD` value. Homebrew's `postgresql@18` is keg-only, so on a Mac the first two lines start it and put its commands on the `PATH`:",
    "",
    "    brew services start postgresql@18",
    '    export PATH="$(brew --prefix postgresql@18)/bin:$PATH"',
    `    createuser -s -P ${key}_user`,
    `    createdb -O ${key}_user ${key}_dashboard`,
    "",
    "On Linux, run the last two as the `postgres` user instead:",
    "",
    `    sudo -u postgres createuser -s -P ${key}_user`,
    `    sudo -u postgres createdb -O ${key}_user ${key}_dashboard`,
    "",
    "Then build the schema and make the first commit:",
    "",
    "    cd pipeline && uv run alembic upgrade head && cd ..",
    '    git add -A && git commit -m "Adapt the dashboard" && git push',
    "",
    "## 8. The first live run",
    "",
    "    uv run python -m pipeline.main --days-back 365 --batch --export",
    "    uv run python -m pipeline.main --clinical-trials --export",
    "    deno task geocode",
    "    uv run python -m pipeline.main --sync-external-data --sync-annotations --export",
    "",
    "The recall measurement counts every PMID `data/table1.json` cites as a gold paper, so an export that adds a reference changes the set step 6 measured: this one does, and so can any later run, a weekly one included. After such an export, measure again and record the cassettes afresh:",
    "",
    "    uv run python -m scripts.measure_recall --write-baseline",
    "    rm -r tests/pipeline/cassettes/test_query_recall_gold",
    "    uv run pytest tests/pipeline/test_query_recall_gold.py --record-mode=once",
    "",
    "Then replace the seven strings in `PROTECTED_DATA_SENTINELS` (`server/protected_data_build.ts`) with strings that exist only in your new `data/`, and recapture the README's screenshots, which still show the upstream disease (this needs libwebp's `cwebp`: `brew install webp`, or the `webp` package on Debian and Ubuntu):",
    "",
    "    deno task screenshots",
    "",
    "Then run the checks again, and commit.",
    "",
    "## 9. Deploy",
    "",
    `On Deno Deploy, create the project with the project name \`${project}\` from your GitHub repository, set \`DASHBOARD_PASSPHRASE\` (without the quotes \`.env\` needs) and \`DASHBOARD_SESSION_SECRET\`, and follow \`.claude/skills/deploy/SKILL.md\` for the build settings. Once the site answers, write its URL into \`hosting.url\` in \`disease/manifest.json\` and into \`disease/README.md\`, and commit.`,
    "",
  ];
  return wrap80(lines.join("\n"));
}
